<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita0a1e12c94c75c5e68fe9cf5e1f3f9b2
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita0a1e12c94c75c5e68fe9cf5e1f3f9b2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita0a1e12c94c75c5e68fe9cf5e1f3f9b2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita0a1e12c94c75c5e68fe9cf5e1f3f9b2::$classMap;

        }, null, ClassLoader::class);
    }
}
